version: '3.0'
services:
  
  web:
    container_name: web
    ports:
      - "80:80" # NECESSARY ports for Deployment
    build:
      context: ./Web
      dockerfile: Dockerfile
  
  pacman_webgl:
    container_name: pacman_webgl
    restart: always
    ports:
      - "8001:80"
    build:
      context: ./PacManUnity-web-version
      dockerfile: Dockerfile