version: '3.0'
services:
  web:
    container_name: web
    ports:
      - "80:5000" # NECESSARY ports for Deployment
    build:
      context: ./Web
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    container_name: database
    restart: always
    ports:
      - "3306:3306" # NECESSARY ports for Deployment
    build:
      context: ./MySQL_DB
      dockerfile: Dockerfile
