version: '3.0'
services:
  web:
    container_name: web
    ports:
      - "80:80" # NECESSARY ports for Deployment
    build:
      context: ./Web
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    container_name: database
    restart: always
    ports:
      - "3306:3306" # NECESSARY ports for Deployment
    build:
      context: ./DB
      dockerfile: Dockerfile

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    environment:
        PMA_HOST: bd

