CREATE DATABASE PROFIL;
CREATE TABLE PROFIL.JOUEUR(ID VARCHAR(50) PRIMARY KEY, MDP VARCHAR(50));
INSERT INTO PROFIL.JOUEUR(`ID`, `MDP`) VALUES ('jerome','1111');
INSERT INTO PROFIL.JOUEUR(`ID`, `MDP`) VALUES ('bastien','1111');